services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: polyretro
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - polyretro_network

    webserver:
        image: nginx:alpine
        container_name: polyretro_webserver
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - polyretro_network

    db:
        image: mysql:8.0
        container_name: polyretro_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: polyretro_database
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
        ports:
            - "3336:3306"
        networks:
            - polyretro_network
        volumes:
            - polyretro_db_data:/var/lib/mysql

volumes:
    polyretro_db_data:

networks:
    polyretro_network:
